### ISSUE TITLE
SqliteError: ../../resources/libsimple.so: 无法打开共享对象文件: 没有那个文件或目录

### ISSUE THREAD

**Issue by mrpengxinwen** [wangfenjin/simple#153]
提问之前先看一下：https://github.com/wangfenjin/simple/issues/87
const simple = "../../resources/libsimple" 
db_document.loadExtension(simple)

SqliteError: ../../resources/libsimple.so: 无法打开共享对象文件: 没有那个文件或目录
    at Database.loadExtension (/home/mkel-7/code/node_modules/better-sqlite3/lib/methods/wrappers.js:19:14)
    at initDB (/home/mkel-7/code/out/main/fileProcessModule-82a36bdf.js:986:17)
    at Module.<anonymous> (/home/mkel-7/code/out/main/fileProcessModule-82a36bdf.js:805:34)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:101:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:165:24) {
  code: 'SQLITE_ERROR'

the path is right, but it still report this error! why?

**Comment by wuxunfeng666** [comment]
我前两天也碰到类似事情。

如果你下的是 aarch64 的包，里面的 .so 实际上是 x86-64 的，需要自己重新编译。。

**Comment by mrpengxinwen** [comment]
绝对路径能解决

**Comment by mrpengxinwen** [comment]
绝对路径能解决
